"""
Dual-branch spectral-spatial neural network training script with ablation options.

This script trains a TensorFlow 1.x dual-branch model for binary geochemical
prediction. The spectral branch uses a bidirectional GRU to model the ordered
feature channels at the center pixel of each patch, while the spatial branch uses
a CNN to learn spatial patterns from the full image patch. Optional spectral
attention, spatial attention, causal feature ordering, geological constraint
weighting, and branch-level ablation settings can be enabled or disabled through
command-line arguments.

The script loads preprocessed `.npy` datasets generated by the preprocessing
script, combines the training and validation samples, and performs stratified
K-fold cross-validation. For each fold, the best model checkpoint is saved based
on validation F1-score. After training, the script ensembles the saved fold
models, evaluates them on the original validation set, and optionally extracts
spectral and spatial attention maps for known deposit locations.

Required input files:

* `X_train.npy`, `y_train.npy`
* `X_val.npy`, `y_val.npy`
* `coords_train.npy`, `coords_val.npy` if geological constraints or attention
  extraction are required
* `geological_weights.npy` if `--use_geo` is enabled
* `causal_feature_order_custom.npy` if `--use_causal` is enabled
* `Au_deposits0.tif` if attention maps for deposit locations are required

Example usage:

* Train the full model with default settings:
  `python train_model.py`

* Disable geological constraints:
  `python train_model.py --no_geo`

* Train only the spectral branch:
  `python train_model.py --branch spectral`

* Disable spectral and spatial attention:
  `python train_model.py --no_spectral_att --no_spatial_att`

Main outputs:

* Best fold checkpoints saved under `D:\SSAN_Checkpoints`
* `spectral_attention_on_deposits.npy`
* `spatial_attention_on_deposits.npy`
* `spectral_attention_heatmap.png`
* `spatial_attention_subplots.png`
* Ensemble evaluation metrics printed to the console
  """

from __future__ import division, print_function, absolute_import

import os
import time
import argparse
from pathlib import Path

import numpy as np
import tensorflow.compat.v1 as tf

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    matthews_corrcoef,
    confusion_matrix,
    cohen_kappa_score,
)

try:
    import matplotlib.pyplot as plt
    import seaborn as sns

except ImportError:

    plt = None
    sns = None

try:
    import rasterio
except ImportError:

    rasterio = None

tf.disable_v2_behavior()


def get_args():
    parser = argparse.ArgumentParser(
        description="Dual-Branch Model Training with Ablation Study Switches"
    )
    parser.add_argument(
        "--use_causal",
        action="store_true",
        default=True,
        help="Enable causal feature ordering.",
    )
    parser.add_argument(
        "--no_causal",
        action="store_false",
        dest="use_causal",
        help="Disable causal feature ordering.",
    )

    parser.add_argument(
        "--use_geo",
        action="store_true",
        default=False,
        help="Enable geological constraints.",
    )
    parser.add_argument(
        "--no_geo",
        action="store_false",
        dest="use_geo",
        help="Disable geological constraints.",
    )

    parser.add_argument(
        "--use_spectral_att",
        action="store_true",
        default=True,
        help="Enable spectral attention.",
    )
    parser.add_argument(
        "--no_spectral_att",
        action="store_false",
        dest="use_spectral_att",
        help="Disable spectral attention.",
    )

    parser.add_argument(
        "--use_spatial_att",
        action="store_true",
        default=True,
        help="Enable spatial attention.",
    )
    parser.add_argument(
        "--no_spatial_att",
        action="store_false",
        dest="use_spatial_att",
        help="Disable spatial attention.",
    )

    parser.add_argument(
        "--branch",
        type=str,
        default="full",
        choices=["full", "spectral", "spatial"],
        help="Select model branch.",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=400,
        help="Maximum number of training steps/epochs.",
    )
    parser.add_argument(
        "--n_splits",
        type=int,
        default=5,
        help="Number of splits for K-Fold Cross-Validation.",
    )
    args = parser.parse_args()
    return args



def load_data(args):

    X_train = np.load("X_train.npy")
    y_train = np.load("y_train.npy")
    X_val = np.load("X_val.npy")
    y_val = np.load("y_val.npy")

    X_train = np.nan_to_num(X_train).astype(np.float32)
    X_val = np.nan_to_num(X_val).astype(np.float32)

    coords_val = np.load("coords_val.npy") if os.path.exists("coords_val.npy") else None

    coords_train, geological_weights_map = None, None
    feature_order = None

    if args.use_geo:
        if os.path.exists("coords_train.npy") and os.path.exists("geological_weights.npy"):
            coords_train = np.load("coords_train.npy")
            geological_weights_map = np.load("geological_weights.npy")
        else:
            args.use_geo = False
    else:
        print("Geological constraints disabled by command-line flag.")

    if args.use_causal:
        try:
            causal_order_file = "causal_feature_order_custom.npy"
            if not os.path.exists(causal_order_file):
                raise FileNotFoundError(f"Causal order file not found: {causal_order_file}")

            tif_dir = Path("geochemical_data")
            original_feature_order = sorted([f.stem for f in tif_dir.glob("*.tif")])

            feature_order = np.load(causal_order_file, allow_pickle=True).tolist()
            original_index_map = {name: i for i, name in enumerate(original_feature_order)}
            reorder_indices = [original_index_map[name] for name in feature_order if name in original_index_map]

            if len(reorder_indices) != len(feature_order):
                args.use_causal = False
            else:
                X_train = X_train[:, :, :, reorder_indices]
                X_val = X_val[:, :, :, reorder_indices]

        except (FileNotFoundError, KeyError) as e:
            args.use_causal = False
    else:
        print("\n--- Skipping causal feature ordering ---")


    if coords_train is not None:
        print(f" coords_train shape: {coords_train.shape}")

    return X_train, y_train, coords_train, geological_weights_map, args, feature_order


def plot_and_save_attention_visuals(spectral_weights, spatial_weights, feature_names=None):

    if plt is None or sns is None:

        return

    try:
        plt.rcParams.update(
            {
                "font.family": "serif",
                "font.serif": ["Times New Roman"],
            }
        )
    except Exception as e:
        print("error")

    num_deposits, num_features = spectral_weights.shape

    plt.figure(figsize=(20, 0.5 * num_deposits + 1))
    ax = sns.heatmap(spectral_weights, cmap="turbo", linewidths=0.5)

    y_labels = [f"Deposit {i + 1}" for i in range(num_deposits)]
    ax.set_yticks(np.arange(num_deposits) + 0.5)
    ax.set_yticklabels(y_labels, rotation=0)

    if feature_names and len(feature_names) == num_features:
        ax.set_xticks(np.arange(num_features) + 0.5)
        ax.set_xticklabels(feature_names, rotation=90, fontsize=8)
    else:
        ax.set_xlabel("Feature Index")

    ax.set_title("Spectral Attention Weights for Matched Deposits", fontsize=16)
    plt.tight_layout()
    spectral_fig_path = "spectral_attention_heatmap.png"
    plt.savefig(spectral_fig_path, dpi=300)
    plt.close()

    ncols = 5
    nrows = (num_deposits + ncols - 1) // ncols
    fig, axes = plt.subplots(
        nrows=nrows,
        ncols=ncols,
        figsize=(3 * ncols, 3 * nrows),
        squeeze=False,
    )

    vmin, vmax = np.min(spatial_weights), np.max(spatial_weights)


    for i in range(num_deposits):
        row, col = i // ncols, i % ncols
        ax = axes[row, col]
        sns.heatmap(
            spatial_weights[i],
            ax=ax,
            cmap="turbo_r",
            vmin=vmin,
            vmax=vmax,
            cbar=False,
            square=True,
        )
        ax.set_title(f"Deposit {i + 1}")
        ax.set_xticks([])
        ax.set_yticks([])


    for i in range(num_deposits, nrows * ncols):
        row, col = i // ncols, i % ncols
        fig.delaxes(axes[row, col])


    fig.subplots_adjust(right=0.9)
    cbar_ax = fig.add_axes([0.92, 0.15, 0.03, 0.7])
    norm = plt.Normalize(vmin=vmin, vmax=vmax)
    sm = plt.cm.ScalarMappable(cmap="turbo", norm=norm)
    sm.set_array([])
    fig.colorbar(sm, cax=cbar_ax)

    spatial_fig_path = "spatial_attention_subplots.png"
    plt.savefig(spatial_fig_path, dpi=300)
    plt.close()



def extract_and_save_attention_maps(
    model_paths_list,
    window_size,
    X_train_full,
    coords_train_full,
    X_val_full,
    coords_val_full,
    feature_order=None,
):

    if rasterio is None:
        print("Skipping attention extraction because 'rasterio' library is not available.")
        return

    if coords_train_full is not None:
        X_full = np.concatenate((X_train_full, X_val_full), axis=0)
        coords_full = np.concatenate((coords_train_full, coords_val_full), axis=0)
    else:
        print("Warning: 'coords_train.npy' not found. Searching only in validation set.")
        X_full, coords_full = X_val_full, coords_val_full

    if coords_full is None:
        print("Error: No coordinate files found. Cannot perform attention extraction.")
        return

    deposit_tif_path = "Au_deposits0.tif"
    if not os.path.exists(deposit_tif_path):
        print(f"Warning: Deposit location file '{deposit_tif_path}' not found.")
        return

    with rasterio.open(deposit_tif_path) as src:
        deposit_mask = src.read(1)
        deposit_coords = set(map(tuple, np.argwhere(deposit_mask == 1)))

    if not deposit_coords:
        print(f"Warning: No deposit points (value=1) found in '{deposit_tif_path}'.")
        return

    full_coord_map = {tuple(coord): i for i, coord in enumerate(coords_full)}
    deposit_indices_in_full_set = [full_coord_map[coord] for coord in deposit_coords if coord in full_coord_map]

    if not deposit_indices_in_full_set:
        print("Warning: Exact deposit coordinates not found in dataset. Using nearest samples instead.")
        coords_array = np.array(coords_full)

        for dep_coord in deposit_coords:
            dists = np.sum((coords_array - np.array(dep_coord)) ** 2, axis=1)
            nearest_idx = int(np.argmin(dists))
            deposit_indices_in_full_set.append(nearest_idx)

        deposit_indices_in_full_set = list(set(deposit_indices_in_full_set))
        print(f"Matched {len(deposit_indices_in_full_set)} nearest samples for attention extraction.")

    deposit_samples_spatial = X_full[deposit_indices_in_full_set]
    num_components = deposit_samples_spatial.shape[3]
    deposit_samples_spectral = deposit_samples_spatial[:, window_size // 2, window_size // 2, :].reshape(
        -1, num_components, 1
    )

    all_spectral_weights, all_spatial_weights = [], []

    for i, model_path in enumerate(model_paths_list):
        print(f" > Processing model {i + 1}/{len(model_paths_list)} from: {model_path}")
        tf.reset_default_graph()

        with tf.Session() as sess:
            meta_file = model_path + ".meta"
            if not os.path.exists(meta_file):
                print(f" Error: Meta graph file not found at '{meta_file}'. Skipping this model.")
                continue

            saver = tf.train.import_meta_graph(meta_file)
            saver.restore(sess, model_path)
            graph = tf.get_default_graph()

            try:
                spe_X = graph.get_tensor_by_name("spe_X:0")
                spa_X = graph.get_tensor_by_name("spa_X:0")
                keep_prob = graph.get_tensor_by_name("keep_prob:0")
                is_training = graph.get_tensor_by_name("is_training:0")
                spectral_attention_tensor = graph.get_tensor_by_name("SpectralAttention/attention_weights:0")
                spatial_attention_tensor = graph.get_tensor_by_name(
                    "ACNN/SpatialInputAttention/attention_weights:0"
                )
            except KeyError as e:
                print(f" Error: Could not find attention tensor in graph for model {model_path}: {e}. Skipping.")
                continue

            spectral_weights, spatial_weights = sess.run(
                [spectral_attention_tensor, spatial_attention_tensor],
                feed_dict={
                    spe_X: deposit_samples_spectral,
                    spa_X: deposit_samples_spatial,
                    keep_prob: 1.0,
                    is_training: False,
                },
            )

            all_spectral_weights.append(spectral_weights)
            all_spatial_weights.append(spatial_weights.reshape(-1, window_size, window_size))

    if not all_spectral_weights:
        print("!!! No attention weights could be extracted from any model. Aborting. !!!")
        return
    ensembled_spectral_weights = np.mean(all_spectral_weights, axis=0)
    ensembled_spatial_weights = np.mean(all_spatial_weights, axis=0)

    np.save("spectral_attention_on_deposits.npy", ensembled_spectral_weights)
    print(
        "Saved integrated spectral attention weights. "
        f"Shape: {ensembled_spectral_weights.shape}\n"
        "File saved as: spectral_attention_on_deposits.npy"
    )

    np.save("spatial_attention_on_deposits.npy", ensembled_spatial_weights)
    print(
        "Saved integrated spatial attention weights. "
        f"Shape: {ensembled_spatial_weights.shape}\n"
        "File saved as: spatial_attention_on_deposits.npy"
    )

    plot_and_save_attention_visuals(ensembled_spectral_weights, ensembled_spatial_weights, feature_order)
    print("\n--- Attention Map Extraction Finished ---")



def evaluate_ensembled_model(model_paths_list, X_test, y_test, window_size, num_components):

    if not model_paths_list:
        print("Evaluation skipped: No models to evaluate.")
        return

    all_probabilities = []

    spec_test = X_test[:, window_size // 2, window_size // 2, :].reshape(-1, num_components, 1)
    spatials_test = X_test

    for i, model_path in enumerate(model_paths_list):
        print(f" > Predicting with model {i + 1}/{len(model_paths_list)}...")
        tf.reset_default_graph()

        with tf.Session() as sess:
            try:
                saver = tf.train.import_meta_graph(model_path + ".meta")
                saver.restore(sess, model_path)
                graph = tf.get_default_graph()

                spe_X = graph.get_tensor_by_name("spe_X:0")
                spa_X = graph.get_tensor_by_name("spa_X:0")
                keep_prob = graph.get_tensor_by_name("keep_prob:0")
                is_training = graph.get_tensor_by_name("is_training:0")
                prediction_tensor = graph.get_tensor_by_name("Softmax:0")

                probabilities = sess.run(
                    prediction_tensor,
                    feed_dict={
                        spe_X: spec_test,
                        spa_X: spatials_test,
                        keep_prob: 1.0,
                        is_training: False,
                    },
                )
                all_probabilities.append(probabilities)

            except Exception as e:
                print(f" Error loading or predicting with model {model_path}: {e}. Skipping this model.")

    if not all_probabilities:
        print("Evaluation failed: Could not get predictions from any model.")
        return

    ensembled_probs = np.mean(all_probabilities, axis=0)
    y_prob_final = ensembled_probs[:, 1]

    threshold = 0.4
    y_pred_final = (y_prob_final >= threshold).astype(int)

    print("\n--- Ensemble Model Performance Metrics ---")
    accuracy = accuracy_score(y_test, y_pred_final)
    precision = precision_score(y_test, y_pred_final, zero_division=0)
    recall = recall_score(y_test, y_pred_final, zero_division=0)
    f1 = f1_score(y_test, y_pred_final, zero_division=0)

    try:
        auc = roc_auc_score(y_test, y_prob_final)
        print(f" AUC Score : {auc:.4f}")
    except ValueError:
        print(" AUC Score : Not calculable (only one class present in y_true)")

    mcc = matthews_corrcoef(y_test, y_pred_final)
    kappa = cohen_kappa_score(y_test, y_pred_final)
    cm = confusion_matrix(y_test, y_pred_final)

    print(f" Accuracy : {accuracy:.4f}")
    print(f" Precision : {precision:.4f}")
    print(f" Recall : {recall:.4f}")
    print(f" F1 Score : {f1:.4f}")
    print(f" Matthews Corrcoef: {mcc:.4f}")
    print(f" Cohen's Kappa : {kappa:.4f}")
    print(f" Confusion Matrix :\n{cm}")
    print("------------------------------------------")



def main():
    args = get_args()

    OPTIMAL_LR = 1e-3
    OPTIMAL_BATCH_SIZE = 32
    OPTIMAL_KEEP_PROB = 0.7217406126539583
    OPTIMAL_NUM_HIDDEN = 128
    OPTIMAL_GEO_ALPHA = 4.906504597284301

    print("\n--- Experiment Configuration ---")

    print(f" Model Branch: {args.branch}")
    print(f" Causal Ordering: {args.use_causal}")
    print(f" Geological Constraints: {args.use_geo}")
    print(f" Spectral Attention: {args.use_spectral_att}")
    print(f" Spatial Attention: {args.use_spatial_att}")
    print(f" Cross-Validation Folds: {args.n_splits}")

    print("\n--- Using Optimal Hyperparameters ---")
    print(f" Learning Rate: {OPTIMAL_LR}")
    print(f" Batch Size: {OPTIMAL_BATCH_SIZE}")
    print(f" Keep Probability: {OPTIMAL_KEEP_PROB}")
    print(f" GRU Hidden Units: {OPTIMAL_NUM_HIDDEN}")
    print(f" Max Epochs: {args.epochs}")
    if args.use_geo:
        print(f" Geo Constraint Alpha: {OPTIMAL_GEO_ALPHA}")
    print("--------------------------------\n")

    X_cv, y_cv, coords_cv, geological_weights_map, args, feature_order = load_data(args)

    window_size, num_components = X_cv.shape[1], X_cv.shape[3]
    timesteps, num_input = num_components, 1

    skf = StratifiedKFold(n_splits=args.n_splits, shuffle=True, random_state=42)
    best_model_paths, overall_best_f1 = [], 0.0

    for fold, (train_idx, val_idx) in enumerate(skf.split(X_cv, y_cv)):
        print(f"\n{'=' * 20} FOLD {fold + 1}/{args.n_splits} {'=' * 20}")

        tf.reset_default_graph()

        X_train, X_val = X_cv[train_idx], X_cv[val_idx]
        y_train, y_val = y_cv[train_idx], y_cv[val_idx]

        coords_train = coords_cv[train_idx] if coords_cv is not None else None
        coords_val = coords_cv[val_idx] if coords_cv is not None else None

        spec_train = X_train[:, window_size // 2, window_size // 2, :].reshape(-1, timesteps, num_input)
        spec_val = X_val[:, window_size // 2, window_size // 2, :].reshape(-1, timesteps, num_input)

        spatials_train, spatials_val = X_train, X_val

        y_train_oh = np.eye(2)[y_train.astype(int)]
        y_val_oh = np.eye(2)[y_val.astype(int)]

        geo_weights_val = np.zeros(len(y_val))
        if args.use_geo and coords_val is not None and geological_weights_map is not None:
            geo_weights_val = geological_weights_map[coords_val[:, 0], coords_val[:, 1]]


        num_hidden, num_classes, ATTENTION_SIZE = OPTIMAL_NUM_HIDDEN, 2, 32
        l2_regularizer = tf.keras.regularizers.l2(0.01)

        s1 = (window_size + 2 - 1) // 2
        s2 = ((window_size + 2 - 1) // 2 + 2 - 1) // 2
        flattened_size = s2 * s2 * 64

        spe_weights = tf.Variable(
            tf.keras.initializers.he_normal()(shape=[num_hidden * 2, num_classes]),
            name="spe_weights",
            regularizer=l2_regularizer,
        )
        spe_biases = tf.Variable(
            tf.zeros_initializer()(shape=[num_classes]),
            name="spe_biases",
        )

        spa_weights = {
            "wc1": tf.Variable(
                tf.keras.initializers.he_normal()(shape=[5, 5, num_components, 32]),
                name="wc1",
                regularizer=l2_regularizer,
            ),
            "wc2": tf.Variable(
                tf.keras.initializers.he_normal()(shape=[5, 5, 32, 64]),
                name="wc2",
                regularizer=l2_regularizer,
            ),
            "wd1": tf.Variable(
                tf.keras.initializers.he_normal()(shape=[flattened_size, 1024]),
                name="wd1",
                regularizer=l2_regularizer,
            ),
            "out": tf.Variable(
                tf.keras.initializers.he_normal()(shape=[1024, num_classes]),
                name="spa_out",
                regularizer=l2_regularizer,
            ),
        }
        spa_biases = {
            "bc1": tf.Variable(tf.zeros_initializer()(shape=[32]), name="bc1"),
            "bc2": tf.Variable(tf.zeros_initializer()(shape=[64]), name="bc2"),
            "bd1": tf.Variable(tf.zeros_initializer()(shape=[1024]), name="bd1"),
            "out": tf.Variable(tf.zeros_initializer()(shape=[num_classes]), name="spa_bd_out"),
        }

        m_weights = {
            "wf1": tf.Variable(
                tf.keras.initializers.he_normal()(shape=[num_classes, 256]),
                name="wf1",
                regularizer=l2_regularizer,
            ),
            "wf1_spa": tf.Variable(
                tf.keras.initializers.he_normal()(shape=[num_classes, 256]),
                name="wf1_spa",
                regularizer=l2_regularizer,
            ),
            "wf2": tf.Variable(
                tf.keras.initializers.he_normal()(shape=[512, 1024]),
                name="wf2",
                regularizer=l2_regularizer,
            ),
            "mout": tf.Variable(
                tf.keras.initializers.he_normal()(shape=[1024, num_classes]),
                name="mout",
                regularizer=l2_regularizer,
            ),
        }
        m_biases = {
            "bf1": tf.Variable(tf.zeros_initializer()(shape=[256]), name="bf1"),
            "bf1_spa": tf.Variable(tf.zeros_initializer()(shape=[256]), name="bf1_spa"),
            "bf2": tf.Variable(tf.zeros_initializer()(shape=[1024]), name="bf2"),
            "mout": tf.Variable(tf.zeros_initializer()(shape=[num_classes]), name="bf_out"),
        }

        spe_X = tf.placeholder(tf.float32, [None, timesteps, num_input], name="spe_X")
        spa_X = tf.placeholder(tf.float32, [None, window_size, window_size, num_components], name="spa_X")
        Y = tf.placeholder(tf.float32, [None, num_classes], name="Y")
        keep_prob = tf.placeholder(tf.float32, name="keep_prob")
        is_training = tf.placeholder(tf.bool, name="is_training")
        geo_weights = tf.placeholder(tf.float32, [None], name="geo_weights")

        def SpectralAttention(inputs, attention_size, regularizer):
            if isinstance(inputs, tuple):
                inputs = tf.concat(inputs, 2)
            hidden_size = inputs.shape[2].value
            w_omega = tf.get_variable(
                "w_omega",
                [hidden_size, attention_size],
                initializer=tf.random_normal_initializer(stddev=0.1),
                regularizer=regularizer,
            )
            b_omega = tf.get_variable(
                "b_omega",
                [attention_size],
                initializer=tf.random_normal_initializer(stddev=0.1),
                regularizer=regularizer,
            )
            u_omega = tf.get_variable(
                "u_omega",
                [attention_size],
                initializer=tf.random_normal_initializer(stddev=0.1),
                regularizer=regularizer,
            )

            v = tf.tanh(tf.tensordot(inputs, w_omega, axes=1) + b_omega)
            vu = tf.tensordot(v, u_omega, axes=1)
            alphas = tf.nn.softmax(vu, name="attention_weights")
            return tf.reduce_sum(inputs * tf.expand_dims(alphas, -1), 1)

        def ARNN(x, use_attention=True):
            gru_fw = tf.nn.rnn_cell.GRUCell(num_hidden)
            gru_bw = tf.nn.rnn_cell.GRUCell(num_hidden)
            outputs, final_states = tf.nn.bidirectional_dynamic_rnn(gru_fw, gru_bw, x, dtype=tf.float32)

            if use_attention:
                print(" - Spectral branch: Attention ENABLED.")
                with tf.variable_scope("SpectralAttention"):
                    a_out = SpectralAttention(outputs, ATTENTION_SIZE, regularizer=l2_regularizer)
            else:
                print(" - Spectral branch: Attention DISABLED (using final hidden states).")
                a_out = tf.concat(final_states, axis=-1)

            return tf.nn.xw_plus_b(a_out, spe_weights, spe_biases)

        def SpatialAttention(feature_map, regularizer, scope="SpatialAttention"):
            with tf.variable_scope(scope, reuse=tf.AUTO_REUSE):
                _, H, W, C = feature_map.get_shape().as_list()
                w_s = tf.get_variable(
                    "w_s",
                    [C, 1],
                    initializer=tf.truncated_normal_initializer(stddev=0.0001),
                    regularizer=regularizer,
                )
                b_s = tf.get_variable(
                    "b_s",
                    [1],
                    initializer=tf.zeros_initializer(),
                    regularizer=regularizer,
                )

                flat = tf.reshape(feature_map, [-1, C])
                sa_logits = tf.matmul(flat, w_s) + b_s
                sa_logits_reshaped = tf.reshape(sa_logits, [-1, H * W])
                sa = tf.nn.sigmoid(sa_logits_reshaped, name="attention_weights")
                att = tf.reshape(tf.concat([sa] * C, axis=1), [-1, H, W, C])
                return att * feature_map

        def ACNN(x, use_attention=True):
            x = tf.reshape(x, [-1, window_size, window_size, num_components])
            x_input_for_conv = SpatialAttention(x, regularizer=l2_regularizer, scope="SpatialInputAttention") if use_attention else x

            if use_attention:
                print(" - Spatial branch: Attention ENABLED.")
            else:
                print(" - Spatial branch: Attention DISABLED (using raw patch).")

            conv1 = tf.nn.relu(
                tf.nn.conv2d(x_input_for_conv, spa_weights["wc1"], [1, 1, 1, 1], "SAME") + spa_biases["bc1"]
            )
            pool1 = tf.nn.max_pool(conv1, [1, 2, 2, 1], [1, 2, 2, 1], "SAME")
            conv2 = tf.nn.relu(
                tf.nn.conv2d(pool1, spa_weights["wc2"], [1, 1, 1, 1], "SAME") + spa_biases["bc2"]
            )
            pool2 = tf.nn.max_pool(conv2, [1, 2, 2, 1], [1, 2, 2, 1], "SAME")
            flat = tf.layers.flatten(pool2)
            fc1 = tf.nn.relu(tf.matmul(flat, spa_weights["wd1"]) + spa_biases["bd1"])
            fc1 = tf.nn.dropout(fc1, keep_prob)
            return tf.matmul(fc1, spa_weights["out"]) + spa_biases["out"]

        def SSAN_1_model(spe_x, spa_x, branch_to_use="full", use_spectral_att=True, use_spatial_att=True):
            print("Building model components:")
            with tf.variable_scope("ACNN"):
                spa_logit = ACNN(spa_x, use_attention=use_spatial_att)
            spe_logit = ARNN(spe_x, use_attention=use_spectral_att)

            if branch_to_use == "spectral":
                return spe_logit
            if branch_to_use == "spatial":
                return spa_logit

            print("Model configured for FULL (spectral-spatial fusion).")
            spe_logit_bn = tf.layers.batch_normalization(spe_logit, training=is_training)
            spa_logit_bn = tf.layers.batch_normalization(spa_logit, training=is_training)

            spe_fc = tf.nn.dropout(
                tf.nn.relu(tf.matmul(spe_logit_bn, m_weights["wf1"]) + m_biases["bf1"]),
                keep_prob,
            )
            spa_fc = tf.nn.dropout(
                tf.nn.relu(tf.matmul(spa_logit_bn, m_weights["wf1_spa"]) + m_biases["bf1_spa"]),
                keep_prob,
            )
            merge = tf.concat([spe_fc, spa_fc], axis=1)
            m2 = tf.nn.relu(tf.matmul(merge, m_weights["wf2"]) + m_biases["bf2"])
            return tf.matmul(m2, m_weights["mout"]) + m_biases["mout"]

        logits = SSAN_1_model(spe_X, spa_X, args.branch, args.use_spectral_att, args.use_spatial_att)
        prediction = tf.nn.softmax(logits, name="Softmax")

        per_sample_loss = tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits, labels=Y)
        if args.use_geo:
            cross_entropy_loss = tf.reduce_mean(per_sample_loss * (1.0 + OPTIMAL_GEO_ALPHA * geo_weights))
        else:
            cross_entropy_loss = tf.reduce_mean(per_sample_loss)

        reg_losses = tf.get_collection(tf.GraphKeys.REGULARIZATION_LOSSES)
        loss_op = cross_entropy_loss + tf.add_n(reg_losses) if reg_losses else cross_entropy_loss

        optimizer = tf.train.AdamOptimizer(OPTIMAL_LR)
        update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)

        grads, variables = zip(*optimizer.compute_gradients(loss_op))
        grads, _ = tf.clip_by_global_norm(grads, 5.0)

        with tf.control_dependencies(update_ops):
            train_op = optimizer.apply_gradients(zip(grads, variables))

        y_pred_op = tf.argmax(prediction, 1)
        y_prob_op = prediction[:, 1]

        save_dir = r"D:\SSAN_Checkpoints"
        os.makedirs(save_dir, exist_ok=True)

        base_model_name = (
            f"ssan_branch-{args.branch}_causal-{args.use_causal}_geo-{args.use_geo}"
            f"_specATT-{args.use_spectral_att}_spatATT-{args.use_spatial_att}"
        )
        best_model_path_for_fold = os.path.join(save_dir, f"{base_model_name}_best_fold-{fold + 1}.ckpt")
        saver = tf.train.Saver(max_to_keep=1)

        best_val_f1_for_fold, patience, patience_counter = 0.0, 2, 0

        with tf.Session() as sess:
            sess.run(tf.global_variables_initializer())

            for step in range(1, args.epochs + 1):
                idx = np.random.choice(len(spec_train), OPTIMAL_BATCH_SIZE, replace=False)
                spe_b, spa_b, lbl_b = spec_train[idx], spatials_train[idx], y_train_oh[idx]

                geo_weights_b = np.zeros(OPTIMAL_BATCH_SIZE)
                if args.use_geo and coords_train is not None and geological_weights_map is not None:
                    geo_weights_b = geological_weights_map[coords_train[idx][:, 0], coords_train[idx][:, 1]]

                sess.run(
                    train_op,
                    feed_dict={
                        spe_X: spe_b,
                        spa_X: spa_b,
                        Y: lbl_b,
                        keep_prob: OPTIMAL_KEEP_PROB,
                        is_training: True,
                        geo_weights: geo_weights_b,
                    },
                )

                if step % 100 == 0 or step == args.epochs:
                    val_y_pred = sess.run(
                        y_pred_op,
                        feed_dict={
                            spe_X: spec_val,
                            spa_X: spatials_val,
                            Y: y_val_oh,
                            keep_prob: 1.0,
                            is_training: False,
                            geo_weights: geo_weights_val,
                        },
                    )
                    val_f1 = f1_score(y_val, val_y_pred, zero_division=0)
                    print(f"Step {step}: Val F1 = {val_f1:.4f}")

                    if step % 500 == 0:
                        print(
                            f" > Fold {fold + 1}, Step {step}: Val F1 = {val_f1:.4f} "
                            f"(Best this fold: {best_val_f1_for_fold:.4f})"
                        )

                    if val_f1 >= best_val_f1_for_fold:
                        best_val_f1_for_fold, patience_counter = val_f1, 0
                        saver.save(sess, best_model_path_for_fold)
                    else:
                        patience_counter += 1
                        if patience_counter >= patience:
                            print(f"--- Early stopping triggered for fold {fold + 1}. ---")
                            break

        if best_val_f1_for_fold > 0:
            print(f"--- Fold {fold + 1} finished. Best F1-Score: {best_val_f1_for_fold:.4f} ---")
            print(f" Best model saved to: {best_model_path_for_fold}")
            best_model_paths.append(best_model_path_for_fold)

            if best_val_f1_for_fold > overall_best_f1:
                overall_best_f1 = best_val_f1_for_fold
        else:
            print(f"--- Fold {fold + 1} finished but no model was saved. ---")

    print(f"\n{'=' * 20} CROSS-VALIDATION FINISHED {'=' * 20}")

    if not best_model_paths:
        print("!!! No models were successfully trained and saved across all folds. Exiting. !!!")
        return

    print(f"Total of {len(best_model_paths)} models from best folds are ready for integration.")
    print(f"Highest F1-Score achieved across all folds: {overall_best_f1:.4f}")

    X_train_orig, y_train_orig = np.load("X_train.npy"), np.load("y_train.npy")  # noqa: F841 (保留原变量)
    X_val_orig, y_val_orig = np.load("X_val.npy"), np.load("y_val.npy")

    coords_train_orig = np.load("coords_train.npy") if os.path.exists("coords_train.npy") else None
    coords_val_orig = np.load("coords_val.npy") if os.path.exists("coords_val.npy") else None


    original_X_val_reordered = np.copy(X_val_orig)

    if args.use_causal and feature_order:
        try:
            tif_dir = Path("geochemical_data")
            original_feature_order = sorted([f.stem for f in tif_dir.glob("*.tif")])
            original_index_map = {name: i for i, name in enumerate(original_feature_order)}
            reorder_indices = [original_index_map[name] for name in feature_order]

            X_train_orig = X_train_orig[:, :, :, reorder_indices]
            original_X_val_reordered = X_val_orig[:, :, :, reorder_indices]

        except Exception as e:
            print(
                "Warning: Could not re-apply causal order for attention extraction/evaluation. "
                f"This may cause issues. Error: {e}"
            )

    extract_and_save_attention_maps(
        best_model_paths,
        window_size,
        X_train_orig,
        coords_train_orig,
        original_X_val_reordered,
        coords_val_orig,
        feature_order,
    )


    evaluate_ensembled_model(best_model_paths, original_X_val_reordered, y_val_orig, window_size, num_components)


if __name__ == "__main__":
    main()
